troiswa_back_administration:
    path: /admin
    defaults:  {_controller:troiswaBackBundle:Main:index}

troiswa_back_equipes:
    path: /equipes
    defaults:
             _controller: FrameworkBundle:Template:template
             template: "troiswaBackBundle:Main:equipe.html.twig"

troiswa_back_contact:
    path: /contact
    defaults:   {_controller:troiswaBackBundle:Main:contact}

troiswa_back_feedback:
    path: /feedback
    defaults:   {_controller:troiswaBackBundle:Main:feedback}
