<?php

namespace troiswa\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function countCategory()
    {
        $query=$this->createQueryBuilder("cat")
            ->select("count(cat)");
        return $query->getQuery()->getSingleScalarResult();
    }
    public function getStringCategory()
    {
        $query=$this->createQueryBuilder("cat")
            ->where("cat.title LIKE 'ma%'");

        return $query->getQuery()->getResult();
    }
}
