
troiswa_back_resource_statics:
    resource: @troiswaBackBundle/Resources/config/routing/statics.yml

troiswa_back_resource_main:
    resource: @troiswaBackBundle/Resources/config/routing/main.yml

troiswa_back_resource_product:
    resource: @troiswaBackBundle/Resources/config/routing/product.yml
    prefix: /product

troiswa_back_resource_category:
    resource: @troiswaBackBundle/Resources/config/routing/category.yml
    prefix: /category

